language: ruby
rvm:
- 2.1
# Assume bundler is being used, install step will run `bundle install`.
#script: ./script/cibuild
install: bundle install && gem install jekyll html-proofer jekyll-sitemap redcarpet
script: jekyll build && htmlproof ./_site

# branch whitelist
branches:
  only:
  - gh-pages     # test the gh-pages branch
  - master
  - /pages-(.*)/ # test every branch which starts with "pages-"

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
